worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    upstream frontend { server frontend:80; }
    upstream node_server { server node_server:5000; }
    upstream cad_models { server cad_models:8000; }
    upstream arr_models { server arr_models:8001; }
    upstream ecg_digitizer { server ecg_digitizer:8501; }
    # upstream mi_app { server svt_app:8003; }
    # upstream svt_api { server svt_api:8002; }

    server {
        listen 80;

        # Route to React Frontend
        location / {
            proxy_pass http://frontend;
        }

        # Route to Node.js Backend
        location /api/ {
            proxy_pass http://node_server/;
        }

        # Route to CAD Models
        location /cad/ {
            proxy_pass http://cad_models/;
        }

        # Route to Streamlit Digitizer (Streamlit requires specific websocket headers)
        location /digitizer/ {
            proxy_pass http://ecg_digitizer/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}